### ISSUE TITLE
Content Delivery requests are in unfriendly format

### ISSUE THREAD

**Issue by MineshS** [episerver/content-delivery-js-sdk#14]
In version 3.0 of the Content Delivery API the requests are made to an unfriendly url e.g. 

http://localhost:8081/api/episerver/v3.0/content?contentUrl=%2F&matchExact=true&expand=* 

in version 2.0 it was similar to http://localhost:8081/url-segment and request header of accept='application/json' 

![image](https://user-images.githubusercontent.com/45593010/128531284-5c1bfcea-695e-477d-9ea5-593b40d73591.png)

**Comment by JohanPetersson** [comment]
Not sure why this would be a bug? This is just a sample implementation and you can still use friendly URLs in your implementation if you prefer.  The SDK itself does use this URL format however,  since the friendly URLs are optional.
