### ISSUE TITLE
OPE edit in decoupled 

### ISSUE THREAD

**Issue by grohdep** [episerver/content-delivery-js-sdk#33]
I am having a hard time making OPE work in the decoupled sample. 

I am logged in to the CMS server on port 8081, and running the SPA on 8081. 

But no matter what I keep getting the Default (view) mode. 

I guess It has something todo with that the fact that I don't have window.epi?

Can you help me?

**Comment by grohdep** [comment]
Sorry. It works after restart of the servers

**Comment by DeepRed** [comment]
Glad to hear it sorted itself out!
